[package]
name = "summarise"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.6"
ollama-rs = "0.2.1"
serde = "1.0.210"
serde_json = "1.0.128"
sqlx = { version = "0.7.4", features = ["runtime-tokio", "postgres", "tls-rustls", "macros", "chrono"] }
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
twilight-cache-inmemory = "0.15.4"
twilight-gateway = "0.15.4"
twilight-http = "0.15.4"
twilight-model = "0.15.4"
vesper = "0.13.0"
openai-api-rs = "5.0.10"
chrono = "0.4.38"
